# Puerto TCP en el que el servidor web embebido (Tomcat) escucha las peticiones HTTP
server.port=8082
# Nombre lógico del microservicio en Spring Boot (útil para identificación en logs y descubrimiento de servicios)
spring.application.name=mascotas-ordenes
